- name: Install Prometheus and Grafana on Amazon Linux
  hosts: all
  become: true
  tasks:
    # Install necessary dependencies
    - name: Install dependencies (wget, tar, etc.)
      yum:
        name:
          - wget
          - tar
        state: latest

    # Install Prometheus
    - name: Download Prometheus
      get_url:
        url: https://github.com/prometheus/prometheus/releases/download/v2.43.0/prometheus-2.43.0.linux-amd64.tar.gz
        dest: /tmp/prometheus.tar.gz

    - name: Unzip Prometheus
      unarchive:
        src: /tmp/prometheus.tar.gz
        dest: /usr/local/
        remote_src: yes

    - name: Clean up Prometheus tar file
      file:
        path: /tmp/prometheus.tar.gz
        state: absent

    - name: Create Prometheus systemd service file
      copy:
        dest: /etc/systemd/system/prometheus.service
        content: |
          [Unit]
          Description=Prometheus
          After=network.target

          [Service]
          User=root
          ExecStart=/usr/local/prometheus-2.43.0.linux-amd64/prometheus \
            --config.file=/usr/local/prometheus-2.43.0.linux-amd64/prometheus.yml \
            --storage.tsdb.path=/usr/local/prometheus-2.43.0.linux-amd64/data
          Restart=always

          [Install]
          WantedBy=multi-user.target

    - name: Start and enable Prometheus service
      systemd:
        name: prometheus
        state: started
        enabled: true

    # Install Grafana
    - name: Download Grafana
      get_url:
        url: https://dl.grafana.com/oss/release/grafana-9.6.4-1.x86_64.rpm
        dest: /tmp/grafana.rpm

    - name: Install Grafana RPM package
      yum:
        name: /tmp/grafana.rpm
        state: present

    - name: Clean up Grafana RPM file
      file:
        path: /tmp/grafana.rpm
        state: absent

    - name: Start and enable Grafana service
      systemd:
        name: grafana-server
        state: started
        enabled: true

    - name: Open Grafana port in the firewall
      firewalld:
        service: grafana
        permanent: yes
        state: enabled
        immediate: yes

