- name: Install Terraform on Amazon Linux
  hosts: all
  become: true
  tasks:
    - name: Install unzip
      yum:
        name: unzip
        state: latest

    - name: Download Terraform
      get_url:
        url: https://releases.hashicorp.com/terraform/{{ terraform_version }}/terraform_{{ terraform_version }}_linux_amd64.zip
        dest: /tmp/terraform.zip
      vars:
        terraform_version: "1.5.6"

    - name: Unzip Terraform
      unarchive:
        src: /tmp/terraform.zip
        dest: /usr/local/bin/
        remote_src: yes

    - name: Clean up Terraform zip file
      file:
        path: /tmp/terraform.zip
        state: absent

    - name: Ensure Terraform is executable
      file:
        path: /usr/local/bin/terraform
        mode: '0755'

